##### Checks run at pull request #####
# Check quiz formatting
check-quizzes: false
# Check that urls in the content are not broken
url-checker: true
# Render preview of content with changes (Rmd's and md's are checked)
render-preview: true
# Spell check Rmds and quizzes
spell-check: true
# Style any R code
style-code: false
# Test build the docker image if any docker-relevant files have been changed
docker-test: false
# Should URLs be tested periodically?
url-check-periodically: true

##### Renderings run upon merge to main branch #####
# Rendering each platform's content
render-bookdown: rmd
render-leanpub: false
render-coursera: false

## Automate the creation of Book.txt file? TRUE/FALSE?
## This is only relevant if render-leanpub is yes, otherwise it will be ignored
make-book-txt: FALSE

# What docker image should be used for rendering?
# The default is jhudsl/base_ottr:main
rendering-docker-image: 'jhudsl/base_ottr:dev'
