---
title: |
  <center> <u>OTTR Courses</u></center>
  <center> <p style = "color:#986753;">Setup</p></center>
date: "Last updated: `r format(Sys.time(), '%B %d, %Y')`"
output: html_document
css: style.css
---



## Create your OTTR repository from the [OTTR_Template repository](https://github.com/jhudsl/OTTR_Template)

```{r, echo=FALSE, results='asis'}
cow::borrow_chapter(
  doc_path = "chunks/copy.md", 
  repo_name = "jhudsl/cheatsheets")
```

```{r, echo=FALSE, results='asis'}
cow::borrow_chapter(
  doc_path = "chunks/actions.md", 
  repo_name = "jhudsl/cheatsheets")
```

```{r, echo=FALSE, results='asis'}
cow::borrow_chapter(
  doc_path = "chunks/collab.md", 
  repo_name = "jhudsl/cheatsheets")
```

```{r, echo=FALSE, results='asis'}
cow::borrow_chapter(
  doc_path = "chunks/dev.md", 
  repo_name = "jhudsl/cheatsheets")
```

```{r, echo=FALSE, results='asis'}
cow::borrow_chapter(
  doc_path =  "chunks/edit.md", 
  repo_name = "jhudsl/cheatsheets")
```

```{r, echo=FALSE, results='asis'} 
 cow::borrow_chapter(   
   doc_path = "chunks/pages.md", 
   repo_name = "jhudsl/cheatsheets")
```

```{r, echo=FALSE, results='asis'}
 cow::borrow_chapter(   
   doc_path = "chunks/token.md", 
   repo_name = "jhudsl/cheatsheets")
```

```{r, echo=FALSE, results='asis'}
 cow::borrow_chapter(   
   doc_path = "chunks/profile.md", 
   repo_name = "jhudsl/cheatsheets")
```

```{r, echo=FALSE, results='asis'} 
 cow::borrow_chapter(   
   doc_path = "chunks/pull_request.md", 
   repo_name = "jhudsl/cheatsheets")
```

```{r, echo=FALSE, results='asis'}
 cow::borrow_chapter(   
   doc_path = "chunks/search.md", 
   repo_name = "jhudsl/cheatsheets")
```

```{r, echo=FALSE, results='asis'}
 cow::borrow_chapter(   
   doc_path = "chunks/secrets.md", 
   repo_name = "jhudsl/cheatsheets")
```

```{r, echo=FALSE, results='asis'} 
 cow::borrow_chapter(   
   doc_path = "chunks/settings.md", 
   repo_name = "jhudsl/cheatsheets")
```

