---
title: <center> <u> OTTR website </u> </center> <center> <p style = "color:#986753;"> Set Up</p></center>
date: "Last updated: `r format(Sys.time(), '%B %d, %Y')`"
output: html_document
css: css/OTTR_style.css
---


```{r, echo=FALSE, results='asis'}
ottrpal::borrow_chapter(
  doc_path = "chunks/download_header.md",
  tag_replacement = list(
    "{PATH_TO_PNG}" = "https://raw.githubusercontent.com/jhudsl/cheatsheets/refs/heads/main/ottr_quarto_course.png"
    ))
```


```{r, echo=FALSE, results='asis'}
ottrpal::borrow_chapter(
  doc_path = "chunks/starter_template.md",
  tag_replacement = list(
    "{TEMPLATE_NAME}" = "OTTR_Template_Website",
    "{TEMPLATE_URL}" = "https://github.com/jhudsl/OTTR_Template_Website"))
```

```{r, echo=FALSE, results='asis'}
ottrpal::borrow_chapter(
  doc_path = "chunks/create_repository.md")
```

```{r, echo=FALSE, results='asis'}
ottrpal::borrow_chapter(
  doc_path = "chunks/enable_actions.md")
```

```{r, echo=FALSE, results='asis'}
 ottrpal::borrow_chapter(   
   doc_path = "chunks/pages.md")
```

```{r, echo=FALSE, results='asis'}
 ottrpal::borrow_chapter(   
   doc_path = "chunks/token.md")
```

```{r, echo=FALSE, results='asis'}
 ottrpal::borrow_chapter(   
   doc_path = "chunks/secrets.md")
```
