---
output: html_document
css: css/OTTR_style.css
---


<div class = "header_box">
<u>OTTR Quarto Course</u><br><span style = "color:#986753;"> Set Up </span>
</div>



```{r, echo=FALSE, results='asis'}
ottrpal::borrow_chapter(
  doc_path = "chunks/download_header.md",
  tag_replacement = list(
    "{PATH_TO_PNG}" = "https://github.com/jhudsl/cheatsheets/blob/main/pngs/ottr_quarto_course.png?raw=true"
    ))
```


**Last updated: `r format(Sys.time(), '%B %d, %Y')`**

```{r, echo=FALSE, results='asis'}
ottrpal::borrow_chapter(
  doc_path = "chunks/starter_template.md",
  tag_replacement = list(
    "{TEMPLATE_NAME}" = "OTTR_Quarto",
    "{TEMPLATE_URL}" = "https://github.com/fhdsl/OTTR_Quarto"))
```

```{r, echo=FALSE, results='asis'}
ottrpal::borrow_chapter(
  doc_path = "chunks/create_repository.md")
```

```{r, echo=FALSE, results='asis'}
ottrpal::borrow_chapter(
  doc_path = "chunks/enable_actions.md")
```

```{r, echo=FALSE, results='asis'}
 ottrpal::borrow_chapter(   
   doc_path = "chunks/pages.md")
```

```{r, echo=FALSE, results='asis'}
 ottrpal::borrow_chapter(   
   doc_path = "chunks/token.md")
```

```{r, echo=FALSE, results='asis'}
 ottrpal::borrow_chapter(   
   doc_path = "chunks/secrets.md")
```


