---
output:
  html_document:
    includes:
      in_header: ottr_favicon.html
css: css/OTTR_style.css
---

```{r, echo=FALSE, results='asis'}
ottrpal::borrow_chapter(
  doc_path = "chunks/create_ottr_header.md",
  tag_replacement = list(
    "{TITLE}" = "OTTR Course", "{SUBTITLE}" =  "Set Up",
        "{PATH_TO_PNG}" = "https://github.com/ottrproject/cheatsheets/blob/main/pngs/ottr_course.png?raw=true"
    ))
```


```{r, echo=FALSE, results='asis'}
ottrpal::borrow_chapter(
  doc_path = "chunks/starter_template.md",
    tag_replacement = list(
    "{TEMPLATE_NAME}" = "OTTR_Template",
    "{TEMPLATE_URL}" = "https://github.com/ottrproject/OTTR_Template"))
```

```{r, echo=FALSE, results='asis'}
ottrpal::borrow_chapter(
  doc_path = "chunks/enable_actions.md")
```

```{r, echo=FALSE, results='asis'}
 ottrpal::borrow_chapter(   
   doc_path = "chunks/pages.md")
```

```{r, echo=FALSE, results='asis'}
 ottrpal::borrow_chapter(   
   doc_path = "chunks/token.md")
```

```{r, echo=FALSE, results='asis'}
 ottrpal::borrow_chapter(   
   doc_path = "chunks/secrets.md")
```

```{r, echo=FALSE, results='asis'}
ottrpal::borrow_chapter(
  doc_path = "chunks/create_ottr_footer.md",
  tag_replacement = list(
    "{AUTHORS}" = "Kate Isaac wrote the content and created the original styling, Carrie Wright did the css styling and Carrie Wright and Candace Savonen did the publishing engineering for the cheatsheet. Padmashri Saravanan and Allissa Dillman from [BioDataSage](https://www.biodatasage.com/) worked with Carrie Wright to review and improve the cheatsheet."
    ))
```
