---
output: html_document
css: css/OTTR_style.css
---

```{r, echo=FALSE, results='asis'}
ottrpal::borrow_chapter(
  doc_path = "chunks/create_ottr_header.md",
  tag_replacement = list(
    "{TITLE}" = "OTTR Quarto Website", "{SUBTITLE}" =  "Set Up",
        "{PATH_TO_PNG}" = "https://github.com/jhudsl/cheatsheets/blob/main/pngs/ottr_quarto_website.png?raw=true"
    ))
```

```{r, echo=FALSE, results='asis'}
ottrpal::borrow_chapter(
  doc_path = "chunks/starter_template.md",
  tag_replacement = list(
    "{TEMPLATE_NAME}" = "OTTR_Quarto_Website",
    "{TEMPLATE_URL}" = "https://github.com/fhdsl/OTTR_Quarto_Website"))
```


```{r, echo=FALSE, results='asis'}
ottrpal::borrow_chapter(
  doc_path = "chunks/enable_actions.md")
```

```{r, echo=FALSE, results='asis'}
 ottrpal::borrow_chapter(   
   doc_path = "chunks/pages.md")
```

```{r, echo=FALSE, results='asis'}
 ottrpal::borrow_chapter(   
   doc_path = "chunks/token.md")
```

```{r, echo=FALSE, results='asis'}
 ottrpal::borrow_chapter(   
   doc_path = "chunks/secrets.md")
```
